Update docs: Use current `brew` install syntax for `cask`
The readme advises this outdated syntax:

```
brew cask install session-manager-plugin
```

...which fails in current `brew` with:

```
Error: Invalid usage: Unknown command: brew cask
```

Looking at the docs for this package:

https://formulae.brew.sh/cask/session-manager-plugin

...we can see that `brew` now advise:

```
brew install --cask session-manager-plugin
```

Note also that this cask is deprecated and has a 'disable date' of  2026-09-01 - but that is Another Problem